version: '3'

services:
  zk:
    build: zk/
  kafka:
    build: kafka/
    depends_on:
    - zk
  acl-scripts:
    build: kafka/
    depends_on:
    - zk
    entrypoint: "sh create-acls-and-auth.sh"
