version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build: .
    depends_on:
    - zookeeper
  acl-scripts:
    build: .
    depends_on:
    - zookeeper
    entrypoint: "sh create-acls.sh"
